### PR TITLE
Add options_ui support

### PR DESCRIPTION
**Pull request by jones-sam**
Community guidelines:

- [x] I have read and understand the
      [contributing guidelines](https://github.com/extend-chrome/.github/blob/master/.github/CONTRIBUTING.md)
      and
      [code of conduct](https://github.com/extend-chrome/.github/blob/master/.github/CODE_OF_CONDUCT.md)

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

### Description

This PR, [addressing this issue](https://github.com/extend-chrome/rollup-plugin-chrome-extension/issues/51), adds support for options_ui, so you can display your options in a native UI popup on the extension page (shown below) as opposed to having its own page.

image

I first had to remove the `CheerioStatic` type and replace it with `cheerio.Root` since `CheerioStatic` is no longer supported. [See this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46006)

I then duplicated the basic extension and created the options_ui extension with the only real difference being that the manifest has `options_ui` instead of `options_page`, and added `options_ui.page` to the manifest parser.

Lastly, I added a error check to see if both `options_ui` and `options_page` exist in the manifest, since only one can exist. I also added a manifest that would trigger the error and a test to go with it.

Let me know what you think!

### CODE REVIEW

**Comment by jones-sam** [comment]
My mistake, I meant to open this PR on my fork.

**Comment by jacksteamdev** [comment]
@jones-sam This is the right place if you want to contribute! Feel free to reopen this when you're ready! 👍

I'be been hearing about the CheerioStatic problem (and it makes sense to me), but I haven't been able to reproduce it. What happens on your computer? Are you using `pnpm`?

**Comment by jones-sam** [comment]
Hey @jacksteamdev , just reopened the PR, let me know what you think!

**Comment by jacksteamdev** [comment]
@jones-sam Thanks for this PR! I'll have time to take a look and merge it sometime this week. I'll let you know if I have any feedback. Have a great week! 🙂

**Comment by jacksteamdev** [comment]
@jones-sam Looks really good! Thanks for the PR! Love the well organized commits.

**Comment by jones-sam** [comment]
Great! Glad I could help

**Pull request merged**
