### PR TITLE
WIP - Vite Support

### PR DESCRIPTION
**Pull request by jacksteamdev**
This isn't ready yet, but the tests are passing!

## TODO

- [x] Refactor integration tests so tests are co-located with example extensions
- [x] Remove excessive unit tests, they're covered in integration tests
- [x] Add Vite build and serve integration tests 
- [x] Add MV3 e2e tests using Playwright
- [x] Add support for `vite build`
- [x] Output MV3 files for `vite serve`
- [x] Add `emitFile` adaptor for `vite serve`
- [x] Refactor MV2 logic to match MV3
- [x] Output MV2 files for `vite serve`
- [ ] Make automatic permissions detection Vite compatible
- [ ] Add MV2 HMR support for html files
- [ ] Add MV2 content script reloading
- [ ] Add MV2 background reloading
- [ ] Add MV3 HMR support for html files
- [ ] Add MV3 content script reloading
- [ ] Add MV3 background reloading

### CODE REVIEW

**Comment by jacksteamdev** [comment]
@AmySteam We can make a beta release tomorrow!

**Comment by npearson72** [comment]
I realize it's premature to test this branch, but I figured I'd give it a try anyway. Wishful thinking?

Here's what's in my `vite.config.js`

```
import { defineConfig } from 'vite';
import reactRefresh from '@vitejs/plugin-react-refresh';
import {
  chromeExtension,
  simpleReloader
} from 'rollup-plugin-chrome-extension';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [chromeExtension(), simpleReloader(), reactRefresh()],
  build: {
    rollupOptions: {
      input: 'manifest.json',
      output: {
        dir: 'dist',
        format: 'esm',
        chunkFileNames: path.join('chunks', '[name]-[hash].js')
      }
    }
  }
});
```

I'm hitting this error:

```
$ vite build
failed to load config from /Users/nathan/Dev/my-vite-react/vite.config.js
error during build:
Error: Cannot find module '/Users/nathan/Dev/my-vite-react/node_modules/rollup-plugin-chrome-extension/lib/index-cjs.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:308:19)
...
```

Are you having more luck with this?

**Comment by AmySteam** [comment]
@npearson72 Thanks for the report! 🙂 

@jacksteamdev can you have a quick look at this tomorrow? Let me know if you have the bandwidth this week, if not let's push it to the next.

**Comment by jacksteamdev** [comment]
@npearson72 Hey, thanks for taking a look at this! :wave: It's not ready yet, I'd really appreciate it if you take a look when it's done. I'll @ you when we've got it ready for testing, shouldn't be long.

**Comment by jacksteamdev** [comment]
@npearson72 I decided to try a different approach for adding Vite support. The legacy code was too brittle to extend easily, so I'm doing a full rewrite. You can track progress in the new PR #117

**Comment by npearson72** [comment]
@jacksteamdev nice. Thanks for the heads-up.

**Pull request closed without merging**
