### PR TITLE
Fix run tests on the Windows

### LINKED ISSUE #137: Does not work on Windows
### Build tool

Vite

### Where do you see the problem?

- [ ] In the browser
- [X] In the terminal

### Describe the bug

`dev` and `build` scripts just hang on the `Building Chrome Extension files...` It appears on Windows only. When running on Linux everything works as expected.

### Reproduction

Create a new extension using this guide https://dev.to/jacksteamdev/create-a-vite-react-chrome-extension-in-90-seconds-3df7
Run it on Windows.

### Logs

```shell
$ npm run dev  
vite v2.7.3 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 606ms.

Building Chrome Extension files...

// and script just hangs here eating CPU
```

### System Info

```shell
System:
    OS: Windows 11
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor             
    Memory: 17.17 GB / 31.91 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chromium (96.0.1054.53)
  npmPackages:
    rollup-plugin-chrome-extension: ^4.0.1-9 => 4.0.1-9 
    vite: ^2.7.3 => 2.7.3
```

### Severity

blocking all usage of RPCE

### PR DESCRIPTION
**Pull request by flipwordit**
Community guidelines:

- [+] I have read and understand the
      [contributing guidelines](https://github.com/extend-chrome/.github/blob/master/.github/CONTRIBUTING.md)
      and
      [code of conduct](https://github.com/extend-chrome/.github/blob/master/.github/CODE_OF_CONDUCT.md)

This PR contains:

- [+] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [+] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [+] no

List any relevant issue numbers:

### CODE REVIEW

**Comment by flipwordit** [comment]
I wanted use this plugin but in doesn't work. I tried use it on windows and ubuntu. Sometimes i had 
"[!] Error: unfinished hook action(s) on exit:
(chrome-extension) buildStart" message. Sometimes it built but didn't work in browser because index.html has reference to main.js.

**Comment by flipwordit** [comment]
It works with node v14.19.0, with 14.16, v16, v17 doesn't.

**Comment by jacksteamdev** [comment]
@flipwordit This is impressive. I can see you put a lot of work into this PR. Thank you. 🙏 

Unfortunately, the code base has changed a lot in the last week (see #200). It looks like this was forked before #200 was merged, and things are more simple now.

Your contribution is very important. Would you be willing to add Windows support to the current version (v4.0.1-16)? Since I've simplified the codebase, it shouldn't be as difficult.

**Comment by flipwordit** [comment]
@jacksteamdev I have seen your changes and tried apply my but current master doesn't work on ubuntu 20.04. I had problem with config because plugins initialize 2 times. I using global variable to config and fixed it but it doesn't work and there are falling tests.
I have error:
`(node:5848) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5848) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I added flag '--unhandled-rejections=strict' but part of tests failed

 After changes build system break point don't stand in need place. Built system combined all files to one and change code and break point places. 

Please fix text and build system for debug and I can help you with windows.

**Comment by jacksteamdev** [comment]
@flipwordit Thanks for the feedback. Your help is greatly appreciated. 👍 

Closing this PR for now, I'll ping you about Windows support when the library is more stable.

**Comment by flipwordit** [comment]
@jacksteamdev Great! I'm waiting your message.

**Pull request closed without merging**
