### PR TITLE
Don't call `Object.keys` on `null` in `getDeepMatches`

### PR DESCRIPTION
**Pull request by mnoorenberghe**
Community guidelines:

- [x] I have read and understand the
      [contributing guidelines](https://github.com/extend-chrome/.github/blob/master/.github/CONTRIBUTING.md)
      and
      [code of conduct](https://github.com/extend-chrome/.github/blob/master/.github/CODE_OF_CONDUCT.md)

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers: #56 

### Description

`chrome.runtime.lastError` is `null` rather than `undefined`[1] in Firefox so the `getDeepMatches` caller in importWrapper--implicit.ts leads to an error being thrown.

This breaks the startup of my extension in Firefox.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1406674

### CODE REVIEW

**Comment by mnoorenberghe** [comment]
The test failure doesn't seem related to my change. It's a TS issue related to the Cheerio module.

**Comment by jacksteamdev** [comment]
@mnoorenberghe Looks good to me! Were you able to get Firefox working with this PR?

**Comment by mnoorenberghe** [comment]
Yes, it gets much further but there are still other bugs to fix.

**Comment by mnoorenberghe** [comment]
Without this fix none of the real background scripts would load IIRC, only a wrapper.

**Comment by jacksteamdev** [comment]
What version of Firefox are you using?

This will be in the next version on NPM! I want to do some real world testing, so probably Tuesday.

**Comment by mnoorenberghe** [comment]
I think it was Firefox Nightly version 90.0 but adding support for Firefox is a side-project so I haven't touched it since I opened this PR. 

The next issue I was looking into was that module imports in content scripts were getting resolved using the page's base URL rather than an extension base URL. I'm not sure whether Firefox or Chrome is correct in this regard (or perhaps it's undefined since extension content scripts aren't [standardized](https://browserext.github.io/browserext/) too much yet).

**Comment by jacksteamdev** [comment]
We'll probably want to switch to creating script tags in the background page to get that side working.

The content script path should be fixable with `chrome.runtime.getURL`.

Looks like we're getting close to full Firefox support!

Thanks for the help, it's golden :medal_sports:

**Pull request merged**
