### PR TITLE
Don't change content-script file names when not wrapping

### PR DESCRIPTION
**Pull request by kjaris**
Community guidelines:

- [ x] I have read and understand the
      [contributing guidelines](https://github.com/extend-chrome/.github/blob/master/.github/CONTRIBUTING.md)
      and
      [code of conduct](https://github.com/extend-chrome/.github/blob/master/.github/CODE_OF_CONDUCT.md)

This PR contains:

- [x ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [ x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [ x] no

List any relevant issue numbers:

### CODE REVIEW

**Comment by jacksteamdev** [comment]
@kjaris Hey, thanks for the PR! Could you provide a use case for this? What problem are you fixing?

**Comment by kjaris** [comment]
> @kjaris Hey, thanks for the PR! Could you provide a use case for this? What problem are you fixing?

When using the plugin and setting wrapContentScripts option to false the outputted manifest.json file is still pointing to  "import-content-script.js" in content-scripts js when that file doesn't exist.

I'm hoping this change fixes the renaming of the file in the manifest.json when wrapContentScripts is false.

**Comment by jacksteamdev** [comment]
@kjaris LGTM! It's up on [NPM](https://www.npmjs.com/package/rollup-plugin-chrome-extension/v/3.6.6). 

[Release Notes](https://github.com/extend-chrome/rollup-plugin-chrome-extension/releases/tag/v3.6.6)

**Comment by kjaris** [comment]
> @kjaris LGTM! It's up on [NPM](https://www.npmjs.com/package/rollup-plugin-chrome-extension/v/3.6.6).
> 
> [Release Notes](https://github.com/extend-chrome/rollup-plugin-chrome-extension/releases/tag/v3.6.6)
itsworking

**Pull request merged**
