### PR TITLE
RPCE 4.0 Vite Support & Plugin System

### PR DESCRIPTION
**Pull request by jacksteamdev**
This PR adds Vite support and some new RPCE specific plugin hooks. Usage with Rollup remains the same.

# Vite Usage

Install (Rollup is currently a required peer dependency):

```sh
npm i rollup-plugin-chrome-extension@beta rollup vite -D
```

Basic `vite.config.ts`:

```typescript
import { chromeExtension, simpleReloader } from 'rollup-plugin-chrome-extension'
import { defineConfig } from 'vite'

export default defineConfig({
  root: 'src',
  build: {
    sourcemap: 'inline',
    outDir: 'dist',
  },
  plugins: [chromeExtension(), simpleReloader()]
})
```

## React HMR

Use the official plugin: [`@vitejs/plugin-react`](https://www.npmjs.com/package/@vitejs/plugin-react)

## MV3 HMR for React and Svelte

~~Give this Chromium bug a star! It blocks HMR in MV3 extensions: https://bugs.chromium.org/p/chromium/issues/detail?id=1247690#c_ts1631117342~~

HMR is now working for MV3 on all HTML pages, including devtools! It works with both React Fast Refresh and Svelte!

# Plugin System

This PR adds some Chrome Extension specific hooks to the basic Rollup/Vite plugin system. These hooks transform the manifest and HTML files in the manifest, as well as top-level assets found in these files: CSS, JSON, images, and others. The hook naming system is as follows:

- A CRX Rollup plugin must have the property { crx: true }
- There are 5 asset types available: css, html, image, json, and raw.
- Transform hooks are named `transformCrx...` followed by the asset type: `transformCrxManifest`, `transformCrxHtml`, etc... These hooks run before it is parsed for assets.
- Render hooks follow the same naming pattern: `renderCrx...` and these hooks run after all assets have been transformed.

Documentation will follow... until then, if you want to try making a plugin, you can import the plugin type for Intellisense. See the builtin [plugin implementations](https://github.com/extend-chrome/rollup-plugin-chrome-extension/tree/xstate-conversion/src) for examples. Plugin files start with "plugin".

# TODO

- [x] NPM Beta Release
- [x] Get HMR working for React
- [x] Get HMR working for Svelte
- [ ] Update documentation

# Features

| features                  | rollup build | rollup watch | vite build | vite watch                |
| ------------------------- | ------------ | ------------ | ---------- | ------------------------- |
| alt manifest formats      | yes          | yes          | yes        | yes                       |
| auto permissions          | yes          | yes          | yes        | yes                       |
| copy assets               | yes          | yes          | yes        | yes                       |
| parse html for assets     | yes          | yes          | yes        | yes                       |
| parse manifest for assets | yes          | yes          | yes        | yes                       |
| reload background         | n/a          | yes          | n/a        | yes                       |
| reload content script     | n/a          | yes          | n/a        | yes                       |
| reload HTML on change     | n/a          | no [^1]  | n/a        | mv2: HMR; mv3: no [^2] |
| reload on asset change    | n/a          | yes          | n/a        | yes                       |
| reload on json change     | n/a          | yes          | n/a        | yes                       |
| reload on manifest change | n/a          | yes          | n/a        | yes                       |
| support react HMR         | n/a          | n/a          | n/a        | mv2: HMR; mv3: no [^2] |
| support typescript        | yes          | yes          | yes        | yes                       |
| transform html as index   | yes          | yes          | yes        | yes                       |
| validate manifest         | yes          | no [^3]  | yes        | no [^3]               |
| scripting api                 | mv2: no; mv3: todo | mv2: no; mv3: todo | mv2: no; mv3: todo | mv2: no; mv3: todo |

[^1]: No reloading for HTML pages in Rollup. A new build triggers a full reload, which blows away the open page.
[^2]: This Chromium bug blocks use of HMR in MV3: https://bugs.chromium.org/p/chromium/issues/detail?id=1247690#c_ts1631117342
[^3]: Currently, an error in watch mode kills the build (for now, just restart watch mode).

# Background

While adding Vite support in #113 it became clear that this plugin's architecture needed an overhaul. It was too hard to extend this plugin given its composed Rollup plugin architecture. The types were too brittle and the behavior was spread between arbitrary modules.

After considering several options, I decided to use XState to manage the core parsing/output of the manifest and html files, and add some RPCE specific hooks to the Rollup/Vite plugin model. We can use this extended RPCE plugin system to add features like ESM wrappers or a hybrid IIFE/ESM build that would be compatible with Firefox. This plugin system will also facilitate developer tools like true HMR when using Vite.

### CODE REVIEW

**Comment by jacksteamdev** [comment]
I'm using XState to manage the core manifest/html file lifecycle. XState lets you create statechart diagrams of how your code works, which will make it easier to understand the lifecycle of a file going from your manifest through RPCE.

Core manifest/html file statechart:
image

File plugin/parsing statechart:
image

**Comment by jacksteamdev** [comment]
@npearson72 This is ready for a test run if you're still interested!

**Comment by npearson72** [comment]
@jacksteamdev sweet! Ton of work... you're a beast. I'll give a whirl this weekend. Cheers.

**Comment by AmySteam** [comment]
Congrats @jacksteamdev! This was a lot of work, but such a game changer! I admire your perseverence! Can't wait to build more extensions together using this fantastic plugin 😀 .  Can't wait for the official launch! 🥳

**Comment by npearson72** [comment]
Running into the following when using with VIte after running the `yarn build` command:

```
➜ yarn build
yarn run v1.22.15
warning package.json: No license field
$ vite build
vite v2.6.13 building for production...
✓ 0 modules transformed.
[chrome-extension] ENOENT: no such file or directory, open '/Users/nathan/Dev/my-vite-react/src/index.html'
error during build:
Error: ENOENT: no such file or directory, open '/Users/nathan/Dev/my-vite-react/src/index.html'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Steps to reproduce:

```
yarn create vite my-vite-react --template react
yarn add -D rollup-plugin-chrome-extension@beta rollup
```

I've add the following to my `vite.config.js`:

```
import { defineConfig } from 'vite';
import {
  chromeExtension,
  simpleReloader
} from 'rollup-plugin-chrome-extension';
import react from '@vitejs/plugin-react';

// https://vitejs.dev/config/
export default defineConfig({
  root: 'src',
  build: {
    sourcemap: 'inline',
    outDir: 'dist'
  },
  plugins: [chromeExtension(), simpleReloader(), react()]
});
```

Run `yarn build`

As an aside, I also tried to copy in the `src` content from `https://github.com/extend-chrome/js-react-boilerplate.git` and modified the `root` to point to the `src/manifest.json`. Also tried renaming `root` to `input`.

None of those options worked.

Vite by default includes the `index.html` file outside of the `src` directory.

When I copied the `index.html` file into the `src` directory, I get the following:


```
➜ yarn build
yarn run v1.22.15
warning package.json: No license field
$ vite build
vite v2.6.13 building for production...
✓ 0 modules transformed.
[chrome-extension] No loader specified for extension ".html"
error during build:
Error: No loader specified for extension ".html"
    at Explorer.getLoaderEntryForFile (/Users/nathan/Dev/my-vite-react/node_modules/cosmiconfig/dist/ExplorerBase.js:98:13)
    at Explorer.loadFileContent (/Users/nathan/Dev/my-vite-react/node_modules/cosmiconfig/dist/Explorer.js:106:25)
    at Explorer.createCosmiconfigResult (/Users/nathan/Dev/my-vite-react/node_modules/cosmiconfig/dist/Explorer.js:112:36)
    at runLoad (/Users/nathan/Dev/my-vite-react/node_modules/cosmiconfig/dist/Explorer.js:126:33)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any ideas?

**Comment by jacksteamdev** [comment]
@npearson72 We'll need to add some example repos for sure :sweat_smile: 

I was able to get a successful build following your instructions by setting the Vite config `build.rollupOptions.input` to `src/manifest.json`. I'll fix that so it works without any special options.

__React plugin__: I've made a wrapper for Vite's official React plugin that limits transformations to the correct files. It's not on NPM yet, but [here's a gist](https://gist.github.com/jacksteamdev/41de7f6d010ebe2f4bd22cad800d9380). The official Vite react plugin doesn't work, since Vite's HMR code only works on HTML files. 

```javascript
import { defineConfig } from "vite";
import {
  chromeExtension,
  simpleReloader,
} from "rollup-plugin-chrome-extension";
// 👇 from https://gist.github.com/jacksteamdev/41de7f6d010ebe2f4bd22cad800d9380
import react from "./react-plugin";

// https://vitejs.dev/config/
export default defineConfig({
  root: "src",
  build: {
    sourcemap: "inline",
    outDir: "dist",
    rollupOptions: {
      input: "src/manifest.json", // 👈 Add this line
    },
  },
  plugins: [chromeExtension(), simpleReloader(), react()],
});
```

```json
{
  "background": {
    "scripts": ["background.js"]
  },
  "content_scripts": [
    {
      "matches": ["http://*/*", "https://*/*"],
      "js": ["content-script.js"],
      "run_at": "document_start"
    }
  ]
}
```

**Comment by jacksteamdev** [comment]
It now works without `build.rollupOptions.input` :heavy_check_mark:

**Comment by hangtwenty** [comment]
This is exciting! 

Got it working locally 🎉   

Note in case something is broken:

* **For now I had to pass `fastRefresh: false` to the React plugin.** I'm using the plugin from your gist. I can provide error messages but I didn't want to muddy the waters in case it's a known issue.
* I updated my Vite version (from "^2.5.10" to "^2.6.14"). I'm not sure if it was necessary but tomorrow I could try downgrading to confirm/deny whether that was needed.

Also by the way:

* _Users of `webextension-polyfill-ts`:_ you might encounter import errors when switching from rollup to vite. They are unrelated to `rollup-plugin-chrome-extension`.
    * It can be resolved using [`antfu/unplugin-auto-import`](https://github.com/antfu/unplugin-auto-import), [as seen here](https://github.com/antfu/vitesse-webext/blob/8d98f92901890bebaf06a340c6774f9b1697c6ff/vite.config.ts#L28-L32). 
        * (If using React/ not-using Vue, remove `"vue"` from the `AutoImport` args.)

**Comment by jacksteamdev** [comment]
@npearson72 @hangtwenty I've pushed a new beta version to NPM. Your feedback has been so very helpful, thanks for taking the time to test the beta version!

The official Vite React plugin should work now by itself, including Fast Refresh, so you can remove the custom plugin file.

https://user-images.githubusercontent.com/23390212/143291809-7159f7b3-21fa-4ee7-8923-e7456f43042f.mp4

### Notes

1. Please install the beta version of Vite (`vite@beta`) for testing. There's a bug in the stable version that I didn't want to try to work around, but they've fixed it in beta.

```sh
npm i rollup-plugin-chrome-extension@beta rollup vite@beta
```

2. All this is MV2 right now. MV3 HMR is still blocked by this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1247690#c_ts1631117342 Any stars this bug can get will be helpful in getting some attention from the Chromium dev team.

3. Fast Refresh is currently only for HTML pages. Changes to background or content scripts will still cause a full extension reload, so the popup would close in this case.

**Comment by npearson72** [comment]
Thanks @jacksteamdev! Just performed a few cursory tests and am able to get a build working.

I am however seeing a CSP injected when I run `vite` (i.e. dev mode in vite) and it blocks adding the extension to Chrome. I'm getting:

```
'content_security_policy.extension_pages': Insecure CSP value "'sha256-HXMlWsq+oNLZssobp+7fA5nLeXdM2SRYQaP17p5P6Ws='" in directive 'script-src'.
```

Any ideas?

**Comment by jacksteamdev** [comment]
> I am however seeing a CSP injected into the manifest when I run `vite` (i.e. dev mode in vite) and it blocks adding the extension to Chrome

Interesting! Is this an MV2 extension?

**Comment by npearson72** [comment]
> > I am however seeing a CSP injected into the manifest when I run `vite` (i.e. dev mode in vite) and it blocks adding the extension to Chrome
> 
> Interesting! Is this an MV2 extension?

No. Should it be?

Here's my manifest:


```
{
  "manifest_version": 3,
  "name": "My Extension",
  "version": "0.1",
  "description": "My Extension",
  "permissions": [],
  "action": {
    "default_popup": "popup.html"
  },
  "background": {
    "service_worker": "js/background.js"
  },
  "content_scripts": [
    {
      "matches": ["<all_urls>"],
      "run_at": "document_end",
      "all_frames": false,
      "js": ["js/content.js"]
    }
  ]
}
```

**Comment by npearson72** [comment]
Also, my testing has included much in the way of analyzing separate imports and proper chunking.

I know Rollup has a bit of an issue with this, at least by way of this ticket: https://github.com/rollup/rollup/issues/2756

Are you aware of this issue and can you shed any light on how your plugin mitigates the problem discussed in that above issue?

**Comment by jacksteamdev** [comment]
React Fast Refresh is blocked on MV3 due to this bug that doesn't allow extended CSPs: https://bugs.chromium.org/p/chromium/issues/detail?id=1247690#c_ts1631117342

Please give it a star if you can, so that the Chromium team can see that it's worth fixing.

**Comment by jacksteamdev** [comment]
I've added the hash to the manifest b/c Vite's implementation of Fast Refresh adds an inline script to HTML files. Inline scripts aren't allowed in Chrome Extensions, but in MV2 you can add a hash to the manifest CSP to get away with it. MV3 doesn't allow that right now due to the bug I mentioned above.

@npearson72 It's building right with MV3 right now b/c I'm expecting this to get fixed, but maybe I should add a validation error for MV3 when inline scripts are detected? What do you think?

**Comment by jacksteamdev** [comment]
> analyzing separate imports and proper chunking

This has been a big problem in the past. The previous version of this plugin used adaptors for content and background scripts, which don't support ESM directly but do support dynamic imports, which in turn do support dynamic imports.

Currently I'm rebuilding the Rollup bundle into a mixed IIFE/ESM bundle, loading files from the original ESM bundle. This is pretty fast b/c everything is in memory.

https://github.com/extend-chrome/rollup-plugin-chrome-extension/blob/871179745828b091e0d37006f65bae6d3d56d445/src/plugin-hybridOutput.ts#L183-L188

**Comment by npearson72** [comment]
> 

That's interesting. I need to confess I'm a bit new to extension building. How do you initialize the popup script if it's not referenced inline?

This is what I have in `popup.html`:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>My Extension</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="main.jsx"></script>
  </body>
</html>
```

**Comment by jacksteamdev** [comment]
Your html is fine! :+1: Vite and the React plugin will transform your HTML to look something like this:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <script type="module" src="http://localhost:3000/pages/popup/@vite/client"></script>
    <script type="module">
import RefreshRuntime from "http://localhost:3000/@react-refresh"
RefreshRuntime.injectIntoGlobalHook(window)
window.$RefreshReg$ = () => {}
window.$RefreshSig$ = () => (type) => type
window.__vite_plugin_react_preamble_installed__ = true
    </script>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>My Extension</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="main.jsx"></script>
  </body>
</html>
```

The Chrome Extension default CSP won't allow loading from localhost or that inline script tag with the import from `@react-refresh`.

**Comment by jacksteamdev** [comment]
@npearson72 @hangtwenty Another beta version is on NPM. I found a way to get HMR working on MV3!

I've tested it with React Fast Refresh and Svelte HMR. Both work as expected, AFAIK

**Comment by onikienko** [comment]
Hi @jacksteamdev 

Thank you for your incredible work.

I tried it on Windows and got this error:

```
$ yarn build
yarn run v1.22.15
warning package.json: No license field
$ vite build
vite v2.7.0-beta.9 building for production...
✓ 0 modules transformed.
[chrome-extension] ENOENT: no such file or directory, open 'C:\Projects\exp\vite-chrome-ext\manifest.json'
error during build:
Error: ENOENT: no such file or directory, open 'C:\Projects\exp\vite-chrome-ext\manifest.json'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

My `vite.config.js` looks like:

```javaScript
export default defineConfig({
    root: 'src', // looks like root is ignored on Windows
    build: {
        sourcemap: 'inline',
        outDir: 'dist',
    },
    plugins: [chromeExtension(), simpleReloader()]
})
```

Looks like `root: 'src'` is ignored on Windows and RPCE looks for manifest.json in the project root. I tried to run the same setup in Ubuntu under WSL2 and it seems to work. Seems like Windows-specific issue.

**Comment by jacksteamdev** [comment]
@onikienko Thanks for helping test this while it's in beta. Your feedback is valuable!

Is this error during `vite serve` or `vite build`? Both?

**Comment by onikienko** [comment]
@jacksteamdev 

For `vite serve` same problem.

There is log:

```
Warning: Event "ERROR" was sent to stopped service "files". This service has already reached its final state, and will not transition.
Event: {"error":{"errno":-4058,"code":"ENOENT","syscall":"open","path":"C:\\Projects\\exp\\vite-chrome-ext\\manifest.json"},"type":"ERROR"}
```

**Comment by jacksteamdev** [comment]
@onikienko I've pushed a patch to NPM: `rollup-plugin-chrome-extension@4.0.1-4`

I've adjusted the search for the manifest, hopefully it works better on Windows :smile: 

If there's still a problem, could you run `vite build --debug` and post the output?

**Comment by onikienko** [comment]
@jacksteamdev 

`vite build` (and `vite serve`) extension works now. But the next issue is that now it puts `dist` folder inside `src`. 😸 

image

But should put `dist` under project's root.

One more issue I noticed with `vite serve`: it does not rebuild on file changes or rebuild only one time. 
It prints:

```
The emitted file "manifest.json" overwrites a previously emitted file of the same name.
rendering chunks (4)...
```
and does not re-build anymore.

**Comment by jacksteamdev** [comment]
> But the next issue is that now it puts `dist` folder inside `src`.

@onikienko I believe this is a Vite bug, where `outDir` is relative to `root` in `vite@^2.7`.
You can verify by running `vite --debug` and checking the config Vite provides.
I've got this working pretty well!

**Comment by jacksteamdev** [comment]
> One more issue I noticed with `vite serve`: it does not rebuild on file changes or rebuild only one time.

@onikienko I totally refactored the build sequence. This should be fixed now :crossed_fingers: 

A new version beta version is on NPM :rocket:

**Comment by jacksteamdev** [comment]
@npearson72 I got Vite HMR working for MV3! Your example should work as is.

Please let me know if you have any problems.

**Comment by npearson72** [comment]
@jacksteamdev can confirm, the manifest is now loading. 👍 

However my popup script isn't.

There reference in my popup html `<script type="module" src="main.jsx"></script>` seems to have three references in my Sources:
Screen Shot 2021-12-11 at 3 56 21 PM

And that first one has the following content:

```
Could not load content for chrome-extension://imhbgicibljjbeiigjjpkphdloblmfhh/main.jsx (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)
```

**Comment by jacksteamdev** [comment]
@npearson72 thanks for helping with this!

I have a couple questions:
- can you share a repo link so I can reproduce the error?
- what OS are using?

**Comment by npearson72** [comment]
> 

@jacksteamdev here's the repo: https://github.com/npearson72/my-app

It's a bit messy... I just threw it together to test the plugin.

I'm on Mac OS v 11.6

**Comment by jacksteamdev** [comment]
@npearson72 Awesome, I can work with this! I'll let you know what I find out.

**Comment by jacksteamdev** [comment]
@npearson72 Thanks for the repo link, I was able to reproduce the issue. It should be working now.

I pushed a new version to NPM: `rollup-plugin-chrome-extension@4.0.1-6`

**Comment by npearson72** [comment]
@jacksteamdev that helped, thank you.

However I've now replaced the vanilla JS I was testing in that main.jsx file with some react and am getting the following extension error:


```
Could not import "/Users/nathan/Dev/my-app/src/main.jsx":
Context
src/popup.html
Stack Trace
src/main.jsx?delay=true&t=1639349613352:8 (anonymous function)
```

I've pushed my changes to that branch I shared with you. Care to take a look?

**Comment by jacksteamdev** [comment]
@npearson72 Funny how different project configs bring bugs to the surface... This has been a big help!

I had to upgrade Vite to `vite@latest` to get it to work.

I've fixed some stuff in the HMR service worker code, mime types and relative paths.

image

I'm pretty excited about how this is coming along. I plan to merge this PR to the main branch this week, but keep it under a beta tag on NPM for a while, until it's pretty stable.

New version is on NPM: `rollup-plugin-chrome-extension@4.0.1-7`

**Comment by npearson72** [comment]
@jacksteamdev hey, nice! It's working.

This should definitely get me started, but I'll keep an eye out for any new quirks.

Appreciate the herculean effort on your part to make this happen.

**Comment by onikienko** [comment]
@jacksteamdev 

Thank you for the updates. 
I just tried again on Windows. And have manifest error again.

<details>
  <summary>vite build --debug</summary>

  ```
$ vite build --debug
  vite:config bundled config file loaded in 414.92ms +0ms
  vite:config using resolved config: {
  vite:config   root: 'C:/Projects/experiments/vite-chrome-ext/src',
  vite:config   build: {
  vite:config     target: [ 'es2019', 'edge88', 'firefox78', 'chrome87', 'safari13.1' ],
  vite:config     polyfillModulePreload: true,
  vite:config     outDir: 'C:\\Projects\\experiments\\vite-chrome-ext\\dist',
  vite:config     assetsDir: 'assets',
  vite:config     assetsInlineLimit: 4096,
  vite:config     cssCodeSplit: true,
  vite:config     cssTarget: [ 'es2019', 'edge88', 'firefox78', 'chrome87', 'safari13.1' ],
  vite:config     sourcemap: 'inline',
  vite:config     rollupOptions: {
  vite:config       input: 'C:\\Projects\\experiments\\vite-chrome-ext\\src\\index.html'
  vite:config     },
  vite:config     minify: 'esbuild',
  vite:config     terserOptions: {},
  vite:config     write: true,
  vite:config     emptyOutDir: null,
  vite:config     manifest: false,
  vite:config     lib: false,
  vite:config     ssr: false,
  vite:config     ssrManifest: false,
  vite:config     reportCompressedSize: true,
  vite:config     chunkSizeWarningLimit: 500,
  vite:config     watch: null,
  vite:config     commonjsOptions: { include: [Array], extensions: [Array] },
  vite:config     dynamicImportVarsOptions: { warnOnError: true, exclude: [Array] }
  vite:config   },
  vite:config   plugins: [
  vite:config     'alias',
  vite:config     'crx:xstate-compat',
  vite:config     'vite:modulepreload-polyfill',
  vite:config     'vite:resolve',
  vite:config     'vite:html-inline-script-proxy',
  vite:config     'vite:css',
  vite:config     'vite:esbuild',
  vite:config     'vite:json',
  vite:config     'vite:wasm',
  vite:config     'vite:worker',
  vite:config     'vite:asset',
  vite:config     'chrome-extension',
  vite:config     'crx:package-json',
  vite:config     'crx:extend-manifest',
  vite:config     'crx:auto-perms',
  vite:config     'crx:pre-validate-manifest',
  vite:config     'crx:background-esm-mv2',
  vite:config     'crx:background-esm-mv3',
  vite:config     'crx:hybrid-format',
  vite:config     'crx:configure-rollup-options',
  vite:config     'crx:transform-index-html',
  vite:config     'simple-reloader',
  vite:config     'vite:define',
  vite:config     'vite:css-post',
  vite:config     'vite:watch-package-data',
  vite:config     'vite:build-html',
  vite:config     'commonjs',
  vite:config     'vite:data-uri',
  vite:config     'rollup-plugin-dynamic-import-variables',
  vite:config     'vite:asset-import-meta-url',
  vite:config     'vite:build-import-analysis',
  vite:config     'vite:esbuild-transpile',
  vite:config     'vite:reporter',
  vite:config     'vite:load-fallback',
  vite:config     'crx:validate-manifest',
  vite:config     'crx:html-map-scripts-to-JS'
  vite:config   ],
  vite:config   configFile: 'C:/Projects/experiments/vite-chrome-ext/vite.config.js',
  vite:config   configFileDependencies: [ 'vite.config.js' ],
  vite:config   inlineConfig: {
  vite:config     root: undefined,
  vite:config     base: undefined,
  vite:config     mode: undefined,
  vite:config     configFile: undefined,
  vite:config     logLevel: undefined,
  vite:config     clearScreen: undefined,
  vite:config     build: {}
  vite:config   },
  vite:config   base: '/',
  vite:config   resolve: { dedupe: undefined, alias: [ [Object], [Object] ] },
  vite:config   publicDir: 'C:\\Projects\\experiments\\vite-chrome-ext\\src\\public',
  vite:config   cacheDir: 'C:\\Projects\\experiments\\vite-chrome-ext\\node_modules\\.vite',
  vite:config   command: 'build',
  vite:config   mode: 'production',
  vite:config   isProduction: true,
  vite:config   server: { fs: { strict: true, allow: [Array], deny: [Array] } },
  vite:config   preview: {
  vite:config     port: undefined,
  vite:config     strictPort: undefined,
  vite:config     clearScreen: [Function: clearScreen],
  vite:config     hasErrorLogged: [Function: hasErrorLogged]
  vite:config   },
  vite:config   packageCache: Map(0) { set: [Function (anonymous)] },
  vite:config   createResolver: [Function: createResolver],
  vite:config   optimizeDeps: {
  vite:config     esbuildOptions: { keepNames: undefined, preserveSymlinks: undefined }
  vite:config   }
  vite:config } +6ms
vite v2.7.1 building for production...
✓ 0 modules transformed.
[chrome-extension] Unable to load manifest at /Projects/experiments/vite-chrome-ext/C:\Projects\experiments\vite-chrome-ext/C:/Projects/experiments/vite-chrome-ext/src/manifest.json
error during build:
Error: Unable to load manifest at /Projects/experiments/vite-chrome-ext/C:\Projects\experiments\vite-chrome-ext/C:/Projects/experiments/vite-chrome-ext/src/manifest.json
    at C:\Projects\experiments\vite-chrome-ext\node_modules\rollup-plugin-chrome-extension\lib\index-cjs.js:1176:17

  ```
</details>

A similar output I have for `vite serve`.

My `vite.config.js`:

```javaScript
export default defineConfig({
    root: 'src',
    build: {
        sourcemap: 'inline',
        outDir: '../dist',
    },
    plugins: [chromeExtension(), simpleReloader()],
})
```

On Linux (using WSL2) everything works fine.

**Comment by remixz** [comment]
An issue I've found: If you're trying to make an XHR request in the popup (and possibly other parts of the extension? but currently building an extension with a popup), every network request is getting redirected to the local development server. This is because https://github.com/extend-chrome/rollup-plugin-chrome-extension/blob/xstate-conversion/src/service-worker/code-fetchHandlerForMV3HMR.ts#L7-L10, there's no check to make sure that the URL is a `chrome-extension://` URL, and not an external. If you add a check like this:


```js
self.addEventListener('fetch', (fetchEvent) => {
  const url = new URL(fetchEvent.request.url)
  if (url.protocol === 'chrome-extension:') {
    fetchEvent.respondWith(mapRequestsToLocalhost(url.href))
  }
})
```
 
It makes network requests work as expected. Happy to open a PR with that change, but not sure if you want PRs happening against a WIP branch.

**Comment by jacksteamdev** [comment]
@remixz Please do make a PR! I've merge this PR, so you can proceed as normal.

**Comment by jacksteamdev** [comment]
@hangtwenty Great to hear! Please feel free to open issues as you find them.

I'll be keeping the new major version under the beta tag on NPM, and releasing as the work progresses.

**Comment by jacksteamdev** [comment]
@hangtwenty @npearson72 @remixz @onikienko

Thanks for taking the time to test this plugin while we're getting it working with Vite! I've opened a discussion to track new beta releases and features; see you there!

Vite discussion: #136

**Pull request merged**
